### ISSUE TITLE
Create Windows template

### ISSUE THREAD

**Issue by umasagashi** [umasagashi/umasagashi-app#2]
## TODO

- [x] dart to platform
- [x] capture in platform
- [x] platform to native
- [x] multi-thread in native
- [x] native to platform
- [x] platform to dart
