### ISSUE TITLE
Create Android template

### ISSUE THREAD

**Issue by umasagashi** [umasagashi/umasagashi-app#3]
## TODO

- [x] dart to Java
- [x] capture in Java
- [x] Java to cpp
- [x] multi-thread in cpp
- [x] cpp to Java
- [x] Java to dart
