### ISSUE TITLE
Create iOS template

### ISSUE THREAD

**Issue by umasagashi** [umasagashi/umasagashi-app#4]
## TODO

- [x] dart to Swift
- [x] capture in Swift
- [x] Swift to cpp
- [x] multi-thread in cpp
- [ ] cpp to Swift
- [ ] Swift to dart

**Comment by umasagashi** [comment]
Need physical device to test capture feature.
